### ISSUE TITLE
vercel deployment error

### ISSUE THREAD

**Issue by raji2004** [raji2004/RefreeG-Platform#17]
Failed to compile.
./src/components/ui/windowSize.tsx:34:23
Type error: Binding element 'userSession' implicitly has an 'any' type.
  32 | };
  33 |
> 34 | const ClientHome = ({ userSession }) => {
     |                       ^
  35 |     const size = useWindowSize();
  36 |
  37 |     return (
Error: Command "npm run build" exited with 1

**Comment by Equinox-67** [comment]
This has been resolved.
