### ISSUE TITLE
deployment error

### ISSUE THREAD

**Issue by raji2004** [raji2004/RefreeG-Platform#18]
./src/app/pages/DonationDetail/page.tsx
134:79  Error: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.  react/no-unescaped-entities
./src/components/Comments.tsx
46:15  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
Error: Command "npm run build" exited with 1

https://github.com/raji2004/RefreeG-Platform/tree/RS-94-Code-the-UI-for-the-donation-detail-page

@nomsou please fix this

**Comment by nomsou** [comment]
Alright, I'll fix it
